"use client";
import"../app/globals.css"
import React from "react";
import {  toast,ToastContainer } from 'react-toast'

// The Providers component is not defined here, so we can't analyze its implementation.
// Assuming it's a custom component that wraps the content with various providers like Redux, Context, etc.
import { Providers } from "../redux/provider";

// The metadata object holds information about the page's metadata (title, description).
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The RootLayout component is a layout wrapper that structures the entire page's content.
export default function RootLayout({ children }) {
  return (
    // A minimal HTML structure for the layout.
    <html lang="en">
      <body>
        {/* The Providers component wraps the children, providing necessary context or state management. */}
        <Providers>{children}</Providers>
<ToastContainer position='top-center' delay={3000} />

      </body>
    </html>
  );
}
